pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Checking files"'
                sh '''
                    ls -la
                    echo "Checking fit"
                    fitList=$(grep -rnw 'firstJenkinsProject/test' -e 'fit(')
                    echo $fitList
                    echo "Checking fdescribe"
                    fdescribeList=$(grep -rnw 'firstJenkinsProject/test' -e 'fdescribe(')
                    echo $fdescribeList
                    if [ -z "$fitList" ] && [ -z "$fdescribeList" ]
                    then
                        echo "We are clean."
                    else
                        echo "Should fail"
                        currentBuild.result = 'FAILURE'
                    fi
                    echo "end"
                '''
            }
        }
        stage('2nd Step') {
            steps {
                sh 'echo "Hello World"'
            }
        }
    }
}
