pipeline {
    agent any
    stages {
        stage('Build') {
            options {
                timeout(time: 3, unit: "SECONDS")
            }
            steps {
                sh 'echo "Checking files"'
                sh '''
                    #!/bin/sh
                    ls -la
                    echo "Go to sleep for 2s"
                    sleep(time: 2, unit: "SECONDS")
                    echo "awake"
                    echo "Checking fit"
                    if (grep -rnw 'firstJenkinsProject/test' -e 'fit(') || (grep -rnw 'firstJenkinsProject/test' -e 'fdescribe(')
                    then
                        echo "Should fail"
                        exit 1
                    else
                        echo "We are clean"
                    fi
                    echo "end"
                '''
            }
        }
        stage('2nd Step') {
            steps {
                sh 'echo "Hello World"'
            }
        }
    }
}
