pipeline {
    agent any
    environment {
        secret1 = credentials('plop11')
    }
    stages {
        stage('clone repo') {
            steps {
                sh 'mkdir -p gws'
                sh 'pwd'
                // sh '/opt/homebrew/bin/hg clone --insecure https://hg.gws.genesys.com/hgweb.cgi/gws'
                echo 'This is secret1: ${secret1}'
                echo "This is secret1: ${secret1}"
                dir ('gws') {
                    checkout scm: ([
                        clean: true,
                        $class: 'MercurialSCM',
                        source: 'https://hg.gws.genesys.com/hgweb.cgi/gws',
                        credentialsId: 'hervoch1-okta-secret',
                        installation: 'build-mac',
                        modules: 'cloud-server/agent-desktop',
                        subdir: 'webapp'
                    ])
                }
            }
        }
    }
}