Boolean isMatchingPR

pipeline {
    agent any
    tools {
        nodejs "NODEJS"
    }
    environment {
        MY_ENV_VAR = "1.0.0"
    }
    stages {
        stage('clone repo') {
            steps {
                sh 'mkdir -p gws'
                dir ('gws') {
                    checkout scm: ([
                        $class: 'MercurialSCM',
                        source: 'https://hg.gws.genesys.com/hgweb.cgi/gws',
                        credentialsId: 'hervoch1-okta-secret',
                        installation: 'build-mac'
                    ])
                }
            }
        }
    }
}